variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"


image: maven:latest

cache:
  paths:
    - .m2/repository

build:
  script:
    - mvn clean install -B
    - cat target/site/jacoco/index.html | grep -o 'Total[^%]*%' | sed 's/<.*>/ /; s/Total/Jacoco Coverage Total:/'
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    paths:
      - target/site/jacoco/jacoco.xml
    reports:
      junit:
        - "**/surefire-reports/TEST-*.xml"
        - "**/failsafe-reports/TEST-*.xml"

coverage:
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  needs: 
    - build
  script:
    - python /opt/cover2cover.py target/site/jacoco/jacoco.xml ${CI_PROJECT_DIR}/src/main/java/ > target/cobertura.xml
  artifacts:
    reports:
      cobertura:
        - target/cobertura.xml
  